name: ⏱️ Synchro Taux Promoteur Automatique (4H)

on:
  schedule:
    # Déclenche à la minute 01 pour couvrir TOUTES les heures charnières d'été et d'hiver UTC
    - cron: '1 22,23,2,3,6,7,10,11,14,15,18,19 * * *'
  workflow_dispatch: # Permet toujours le déclenchement manuel

jobs:
  execution_cron:
    runs-on: ubuntu-latest
    steps:
    - name: 📥 Récupération du code
      uses: actions/checkout@v4

    - name: 🐍 Installation de Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: 📦 Installation des dépendances
      run: |
        python -m pip install --upgrade pip
        pip install requests firebase-admin pandas google-cloud-firestore streamlit tzdata

    - name: 🚀 Lancement de la synchronisation des Taux
      env:
        FIREBASE_CREDENTIALS_JSON: ${{ secrets.FIREBASE_CREDENTIALS_JSON }}
      run: python run_cron_taux.py
